// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfFlowKey struct {
	_       structs.HostLayout
	SrcIp   uint32
	DstIp   uint32
	SrcPort uint16
	DstPort uint16
}

type bpfTcpMetrics struct {
	_               structs.HostLayout
	SndCwnd         uint32
	Ssthresh        uint32
	Srtt            uint32
	Retransmissions uint32
	DuplicateAcks   uint32
	BytesAcked      uint64
	PacketsOut      uint32
	RetransOut      uint32
	Sndbuf          uint32
	TcpState        uint8
	CaState         uint8
	CaName          [16]int8
	TimestampNs     uint64
	_               [2]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	bpfMapTcpConnections          = "tcp_connections"
	bpfMapTcpEvents               = "tcp_events"
	bpfProgHandleFastretransAlert = "handle_fastretrans_alert"
	bpfProgHandleTcpAckExit       = "handle_tcp_ack_exit"
	bpfProgHandleTcpProbe         = "handle_tcp_probe"
	bpfProgHandleTcpRetransmitSkb = "handle_tcp_retransmit_skb"
	bpfProgHandleTcpStateChange   = "handle_tcp_state_change"
	bpfProgTraceTcpSetCaState     = "trace_tcp_set_ca_state"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	HandleFastretransAlert *ebpf.ProgramSpec `ebpf:"handle_fastretrans_alert"`
	HandleTcpAckExit       *ebpf.ProgramSpec `ebpf:"handle_tcp_ack_exit"`
	HandleTcpProbe         *ebpf.ProgramSpec `ebpf:"handle_tcp_probe"`
	HandleTcpRetransmitSkb *ebpf.ProgramSpec `ebpf:"handle_tcp_retransmit_skb"`
	HandleTcpStateChange   *ebpf.ProgramSpec `ebpf:"handle_tcp_state_change"`
	TraceTcpSetCaState     *ebpf.ProgramSpec `ebpf:"trace_tcp_set_ca_state"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	TcpConnections *ebpf.MapSpec `ebpf:"tcp_connections"`
	TcpEvents      *ebpf.MapSpec `ebpf:"tcp_events"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	TcpConnections *ebpf.Map `ebpf:"tcp_connections"`
	TcpEvents      *ebpf.Map `ebpf:"tcp_events"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.TcpConnections,
		m.TcpEvents,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	HandleFastretransAlert *ebpf.Program `ebpf:"handle_fastretrans_alert"`
	HandleTcpAckExit       *ebpf.Program `ebpf:"handle_tcp_ack_exit"`
	HandleTcpProbe         *ebpf.Program `ebpf:"handle_tcp_probe"`
	HandleTcpRetransmitSkb *ebpf.Program `ebpf:"handle_tcp_retransmit_skb"`
	HandleTcpStateChange   *ebpf.Program `ebpf:"handle_tcp_state_change"`
	TraceTcpSetCaState     *ebpf.Program `ebpf:"trace_tcp_set_ca_state"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.HandleFastretransAlert,
		p.HandleTcpAckExit,
		p.HandleTcpProbe,
		p.HandleTcpRetransmitSkb,
		p.HandleTcpStateChange,
		p.TraceTcpSetCaState,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_x86_bpfel.o
var _BpfBytes []byte
